CREATE TABLE Attributes (
    id VARCHAR(32),
    fullName VARCHAR(64),
    basic BOOLEAN,
    PRIMARY KEY (id)
);

INSERT INTO Attributes
    (id, fullName, basic)
VALUES
    ('InitWalkVel', 'Initial Walk Velocity', 'false'),
    ('WalkAccel', 'Walk Acceleration?', 'false'),
    ('WalkMaxVel', 'Walk Maximum Velocity', 'false'),
    ('SlowWalkMax', 'Slow Walk Max?', 'false'),
    ('MidWalkPoint', 'Mid Walk Point?', 'false'),
    ('FastWalkMin', 'Fast Walk Min?', 'false'),
    ('Friction', 'Friction/Stop Deccel', 'false'),
    ('DashInitVel', 'Dash Initial Velocity', 'false'),
    ('DashAccelA', 'Dash & Run Acceleration A', 'false'),
    ('DashAccelB', 'Dash & Run Acceleration B', 'false'),
    ('DashTermVel', 'Dash & Run Terminal Velocity', 'false'),
    ('RunAnimScal', 'Run Animation Scaling', 'false'),
    ('RunAccel', 'Run Acceleration?', 'false'),
    ('Unknown14', '????', 'false'),
    ('JumpFrames', 'Jump Startup Lag (Frames)', 'true'),
    ('JumpHInitVel', 'Jump H Initial Velocity', 'false'),
    ('JumpVInitVel', 'Jump V Initial Velocity', 'false'),
    ('JumpMomentMult', 'Ground to Air Jump Momentum Multiplier', 'false'),
    ('JumpHMaxVel', 'Jump H Maximum Velocity', 'false'),
    ('SHVInitVel', 'Shorthop V Initial Velocity', 'false'),
    ('AirJMult', 'Air Jump Multiplier', 'false'),
    ('DblJMult', 'Double Jump Momentum', 'false'),
    ('NumJumps', 'Number of Jumps', 'true'),
    ('Gravity', 'Gravity', 'true'),
    ('TermVel', 'Terminal Velocity', 'true'),
    ('AirMobA', 'Air Mobility A', 'false'),
    ('AirMobB', 'Air Mobility B', 'false'),
    ('MaxAirHVel', 'Max Aerial H Velocity', 'false'),
    ('AirFriction', 'Air Friction', 'false'),
    ('FFTermVel', 'Fast Fall Terminal Velocity', 'true'),
    ('Unknown31', '????', 'false'),
    ('Jab2Window', 'Jab 2 Window?', 'false'),
    ('Jab3Window', 'Jab 3 Window?', 'false'),
    ('ChDirFrames', 'Frames to Change Direction on Standing Turn', 'false'),
    ('Weight', 'Weight', 'true'),
    ('ModelScaling', 'Model Scaling', 'false'),
    ('ShieldSize', 'Shield Size', 'false'),
    ('ShldBrkInitVel', 'Shield Break Initial Velocity', 'false'),
    ('RpdJabWindow', 'Rapid Jab Window', 'false'),
    ('Unknown40', '????', 'false'),
    ('Unknown41', '????', 'false'),
    ('Unknown42', '????', 'false'),
    ('LdgJmpHVel', 'Ledgejump Horizontal Velocity', 'false'),
    ('LdgJmpVVel', 'Ledgejump Vertical Velocity', 'false'),
    ('ThrowVel', 'Item Throw Velocity', 'false'),
    ('Unknown46', '????', 'false'),
    ('Unknown47', '????', 'false'),
    ('Unknown48', '????', 'false'),
    ('Unknown49', '????', 'false'),
    ('Unkonwn50', '????', 'false'),
    ('Unknown51', '????', 'false'),
    ('Unknown52', '????', 'false'),
    ('Unknown53', '????', 'false'),
    ('Unkonwn54', '????', 'false'),
    ('Unknown55', '????', 'false'),
    ('Unknown56', '????', 'false'),
    ('StarDmg', 'Kirby Neutral+B Star Damage', 'false'),
    ('ALag', 'Normal Landing Lag', 'true'),
    ('NLag', 'N-Air Landing Lag', 'true'),
    ('FLag', 'F-Air Landing Lag', 'true'),
    ('BLag', 'B-Air Landing Lag', 'true'),
    ('ULag', 'U-Air Landing Lag', 'true'),
    ('DLag', 'D-Air Landing Lag', 'true'),
    ('VMdlScaling', 'Victory Screen Window Model Scaling', 'false'),
    ('Unknown65', '????', 'false'),
    ('WJmpHVel', 'WallJump H Velocity', 'false'),
    ('WJmpVVel', 'WallJump V Velocity', 'false'),
    ('Unknown68', '????', 'false'),
    ('Unknown69', '????', 'false'),
    ('Unknown70', '????', 'false'),
    ('Unknown71', '????', 'false'),
    ('Unknown72', '????', 'false'),
    ('Unknown73', '????', 'false'),
    ('Unknown74', '????', 'false'),
    ('Unknown75', '????', 'false'),
    ('Unknown76', '????', 'false'),
    ('Unknown77', '????', 'false'),
    ('Unknown78', '????', 'false'),
    ('Unknown79', '????', 'false'),
    ('Unknown80', '????', 'false'),
    ('Unknown81', '????', 'false'),
    ('Unknown82', '????', 'false'),
    ('Unknown83', '????', 'false'),
    ('Unknown84', '????', 'false'),
    ('Unknown85', '????', 'false'),
    ('Unknown86', '????', 'false'),
    ('Unknown87', '????', 'false'),
    ('Unknown88', '????', 'false'),
    ('Unknown89', '????', 'false'),
    ('Unknown90', '????', 'false'),
    ('Unknown91', '????', 'false'),
    ('Unknown92', '????', 'false'),
    ('Unknown93', '????', 'false'),
    ('Unknown94', '????', 'false'),
    ('Unknown95', '????', 'false'),
    ('Unknown96', '????', 'false')
