DROP TABLE IF EXISTS Hitboxes;
DROP TABLE IF EXISTS FrameStrips;
DROP TABLE IF EXISTS CharacterAnimationCommands;
DROP TABLE IF EXISTS AnimationCommandTypes;
DROP TABLE IF EXISTS Animations;
DROP TABLE IF EXISTS CharacterAttributes;
DROP TABLE IF EXISTS Attributes;
DROP TABLE IF EXISTS Characters;
